### ISSUE TITLE
Broken link - can't find on pivnet

### ISSUE THREAD

**Issue by ywei2017** [pivotal-cf/docs-pcf-pws#10]
https://github.com/pivotal-cf/docs-pcf-pws/blob/938f6c583e83fe7e5ace7f5a44462ac26f8c2035/autoscaler/using-autoscaler-cli.html.md.erb#L16

**Comment by scribblingfox** [comment]
Hi @ywei2017! Thanks for your input here--the link is fixed now! If you can't see the autoscaler download page, clear your browser cache and make sure you're logged into PivNet!
