### ISSUE TITLE
Update TAS 5.0 Release Notes Documentation New Feature List & Known Issues List

### ISSUE THREAD

**Issue by PeteLevineA** [pivotal-cf/docs-pcf-pws#108]
To submit content for the TAS IX team to use in writing documentation:

1. Fill out all fields in "Background Information".

1. Review the "Guidelines".

1. Under "Content", write your content, following the "Guidelines".

1. Click "Submit new issue".

We will follow up with you if necessary. Thank you!

### Background Information

Please fill out all of these fields!

* **Link(s) to Pivotal Tracker epic or story/stories:** [Link]
https://vmware.aha.io/bookmarks/feature_boards/7011191997887176542/7288800324483256376
* **Link(s) to any existing documentation:** [Link]
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Service/5.0/tas-for-vms/tas-portal-about-tas-portal.html
* **Versions to which this applies:** [Versions]
5.0
* **Slack user(s) or channel that we might contact (for clarification, review, etc.):** [Usernames or channel name]
https://vmware.slack.com/archives/C03RFSF50VD
### Guidelines

Please include the following information in your write-up:

* Who is the target user--operator, developer, other?
**Developer, Operator of TAS Env etc.**

* What changed in the product, and why?
**Added New TAS Portal Functionality for version 5.0** 

## Content

Please update the release notes of TAS Version 5.0 https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Application-Service/5.0/tas-for-vms/runtime-rn.html 
To include the feature release of TAS Portal for TAS 5.0. In the New Feature's list for TAS for VMs version 5.0. Copy from Kathy here:
Tanzu Application Service Developer Portal supports data persistence (beta) – Developers and platform engineers alike can benefit from a MySQL database integration for persisting data in the software catalog and other plugins used in the Tanzu Application Service Developer Portal. Our engineering team has made great strides in contributing MySQL support to the [Backstage](https://backstage.io/) community.

Also include a link to the TAS Portal 5.0 Documentation

Please include a section in the known issues list:
Tanzu Application Service Developer Portal does not currently include a list of Application Accelerators by default along with the TAS Developer Portal for version 5.0. In order for customers to use application accelerators, the TAS Operator needs to update the "Backstage Configuration" field of the TAS Portal configuration of the TAS tile. Add the following:
`accelerator:`
`  engineUrl: https://${APP_ACCELERATOR_APP_NAME}.${APPS_DOMAIN}`
Currently the creation of software packages from Accelerator Templates only works with in-memory or non-clustered databases. Currently the TAS Portal defaults to the In-memory database
Risk: Due to defaulting to the in-memory database, App Restarts will cause a loss of components in the component list. Users will need to re-register their components.

**Comment by anita-flegg** [comment]
The draft of this content is in the 5.0 release notes now. Ready for review.

**Comment by anita-flegg** [comment]
@PeteLevineA approved -- Closing
