### ISSUE TITLE
Fix wording related to LDAP authentication in docs

### ISSUE THREAD

**Issue by mrosecrance** [pivotal-cf/docs-pcf-pws#133]
### Background Information

Please fill out all of these fields!

* **Link(s) to any existing documentation:** https://docs.vmware.com/en/VMware-Tanzu-Application-Service/5.0/tas-for-vms/auth-sso.html?hWord=N4IghgNiBcIQJmADiAvkA#configure-ldap-as-an-identity-provider-for-tas-for-vms-3

* **Versions to which this applies:** All in support versions which I believe should be TAS 4-6.

* **Slack user(s) or channel that we might contact (for clarification, review, etc.):** Ideally this should go to the uaa team. Daniel Lynch has some context as well

### Guidelines

Please include the following information in your write-up:

* Who is the target user--operator, developer, other?
Operator

* What changed in the product, and why?
Documentation is incorrect which has led to support tickets

Customers Often attempt to add multiple LDAP domains to TAS and find out this is not supported. Our docs do mention we support multiple ldap servers, however, we do not support multiple LDAP domains.  Only a single LDAP forest can be supported for the entire TAS installation.  If they require support for multiple domains and forests then SAML integration is the recommended solution.

## Content
The line:
`To integrate the UAA with one or more LDAP servers:`

Should be changed to
`To integrate the UAA with an LDAP server:` There should be a sub point calling out if they require support for multiple domains and forests then SAML integration is the recommended solution.

**Comment by anita-flegg** [comment]
Hi @mrosecrance , This file is in https://github.com/pivotal-cf/docs-operating-pas.
With the new way the doc URLs are made, it can be quite challenging to find the right repo :)

I made the change in master, 6.0, 5.0, 4.0, 2.13, 2.11 (2.13 and 2.11 are EOGs but are in a grace period until the end of 09/30/2024)
