### ISSUE TITLE
print app name in the autoscale app log 

### ISSUE THREAD

**Issue by sfrancies** [pivotal-cf/docs-pcf-pws#22]
Right now ( until PCF 2.4 ) with app autoscale we only get app guid in the logs, we would want to see app name, so that when the logs are forwarded to splunk, we get readable data to configure any alerts.

**Comment by paigecalvert** [comment]
Hi @sfrancies, 

Thanks for reaching out! This sounds like a feature request, so I want to mention that this documentation repository is maintained by technical writers, not developers or support engineering. For questions about Pivotal Cloud Foundry, please contact Pivotal support: https://support.pivotal.io. If this is not a feature request, could you elaborate on the change that you would like to see made to this documentation? Thanks again!

**Comment by mlimonczenko** [comment]
Hello @sfrancies,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
