### ISSUE TITLE
cf configure-autoscaling is not a registered command error

### ISSUE THREAD

**Issue by vani353** [pivotal-cf/docs-pcf-pws#55]
I have been seeing this issue whenever I try to configure autoscaling for my application from Azure DevOps

**Comment by bhanuReddy2695** [comment]
Any Update on this issue @cf-gitbot  and @vani353 . Because it still persists.

**Comment by vani353** [comment]
@bhanuReddy2695 I haven't heard anything on this yet
@pcf-core-services @cf-gitbot any updates on this issue?

**Comment by ssapra** [comment]
The `configure-autoscaling` command is only available via the `App Autoscaler CLI Plugin`. See the [documentation](https://docs.run.pivotal.io/appsman-services/autoscaler/using-autoscaler-cli.html#install) for more.
