### ISSUE TITLE
App Autoscaler emails notifications

### ISSUE THREAD

**Issue by Shuvrodas** [pivotal-cf/docs-pcf-pws#56]
Manage App Autoscaler Notifications
App Autoscaler emails its event notifications to all space users by default.
The above statement from the doc https://docs.run.pivotal.io/appsman-services/autoscaler/using-autoscaler.html#notifs is not true.
App autoscaler send a notification to the user how has space Developer role  
Please find the discussion with engineering.
https://pivotal-io.atlassian.net/browse/ASCALAR-28

**Comment by erabil** [comment]
Thank you @Shuvrodas! I've fixed the error and it should appear shortly.
