### ISSUE TITLE
Autoscaler email notifications setup unclear

### ISSUE THREAD

**Issue by ctlong** [pivotal-cf/docs-pcf-pws#57]
We were trying to follow the docs [here](https://docs.pivotal.io/application-service/2-9/appsman-services/autoscaler/using-autoscaler.html#notifs) to setup autoscaler with email notifications. However, after following the instructions and seeing autoscaler succeed, we were still failing to receive email notifications.

We found this [KB article](https://community.pivotal.io/s/article/Why-am-I-not-receiving-email-notifications-when-autoscale-events-happen-for-my-application?language=en_US) that told us we need to configure email notifications first, and run the notifications & notifications-ui, as well as some other steps. Please incorporate some of this article into the docs – particularly making it clear that some setup is required to make email notifications work. Thanks.

**Comment by mlimonczenko** [comment]
Hello @ctlong,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
