### ISSUE TITLE
Programmatically configure autoscaler rules

### ISSUE THREAD

**Issue by bogdatov** [pivotal-cf/docs-pcf-pws#7]
This is feature request. 
I would be nice if I can create/enable autoscaling rules (CPU/HTTP) using manifests and/or CFI commands. Instead of manually configuring them in UI.

E.g. I have have 150 apps that require autoscaling between 2 and 5 instances based on CPU load and HTTP throughput. Many developers constantly adding/deploying apps to different environments and we need some automated way of setting up autoscaling.

**Comment by animatedmax** [comment]
Hi @bogdatov 

This documentation repository is maintained by technical writers, not developers or support engineering. 

To make a feature request, or if you have questions about the open source Cloud Foundry project, we recommend that you contact the cf-dev@lists.cloudfoundry.org mailing list, or https://support.pivotal.io for commercial requests.

Thank you.
