### ISSUE TITLE
Please add documentation of the scaling factors feature

### ISSUE THREAD

**Issue by pivotalgeorge** [pivotal-cf/docs-pcf-pws#75]
@hjcalderon10 and I--from the TAS UIs team--have been working on adding scaling factors to the apps-manager scaling configuration form as part of the [TAS-82 Enhacement](https://vmware.aha.io/epics/TAS-E-82). You can see the mockup in [this frame](https://miro.com/app/board/o9J_l1AjwSk=/?moveToWidget=3458764522037099523&cot=14) of the miro board linked in the aha card.

This issue is a request to document this new feature in Apps Manager, most likely on [the existing using-autoscaler page](https://github.com/pivotal-cf/docs-pcf-pws/blob/master/autoscaler/using-autoscaler.html.md.erb)

**Comment by fifthposition** [comment]
@pivotalgeorge @hjcalderon10 We now have an issue template, "Write-Up for Documentation Team", which you can use for documentation requests. If you could create an issue for this feature using that template, we will get started on the documentation. Thank you!

**Comment by anita-flegg** [comment]
This doc work was completed but this Issue was not closed. Closing now so that I can close the Tracker ticket.
