### ISSUE TITLE
[TAS-E-94] Developers can quickly find specific org members in Apps Manager by username.

### ISSUE THREAD

**Issue by jdgonzaleza** [pivotal-cf/docs-pcf-pws#87]
To submit content for the TAS IX team to use in writing documentation:

1. Fill out all fields in "Background Information".

1. Review the "Guidelines".

1. Under "Content", write your content, following the "Guidelines".

1. Click "Submit new issue".

We will follow up with you if necessary. Thank you!

### Background Information

Please fill out all of these fields!

* **Link(s) to Pivotal Tracker epic or story/stories:** [Link]
https://vmware.aha.io/epics/TAS-E-94
https://www.pivotaltracker.com/n/projects/2489404

* **Link(s) to any existing documentation:** [Link]
https://vmware.aha.io/epics/TAS-E-94

* **Versions to which this applies:** [Versions]
capi v1.136.0
* **Slack user(s) or channel that we can contact (for clarification, review, etc.):** [Usernames or channel name]
#tas-user-interface
@gojuan
@ab
@pivotalgeorge
### Guidelines

Please include the following information in your write-up:

* Who is the target user--operator, developer, other?
developers
* What changed in the product, and why?
created new query param so that developers using the org members endpoint can do a fuzzy search by partial usernames
* How does it work, in detail? How does the operator or developer use it?
`GET /organizations/:guid/users?partial_username=user`
* What are the benefits to customers?
Devs can do fuzzy search.
* Are there any example use cases that we can highlight?
`GET /organizations/:guid/users?partial_username=user`
Other things to remember:

* If the CLI is involved, please provide example steps, including example commands to run and example command output.

* Be sure to mention any extensions, plug-ins, or third-party tools that the user will need in order to follow the documentation.

* If the UI is involved, please provide example steps **and screenshots!**

## Content

By adding the new `partial_usernames` query parameter to the `GET /organizations/:guid/users` endpoint, we are enabling CAPI users the ability to do a fuzzy search by username. It is important to mention that `partial_usernames` is an array of strings.
This means that users might find all the users that contain a certain string in their usernames.  This will search by all the users that are registered on UAA. 
In order to run make a request using this new query parameter do the following:
```
curl "https://api.example.org/v3/organizations/:guid/users?partial_usernames=[partial_username_list]" \
  -X GET \
  -H "Authorization: bearer [token]"
``` 
The response will look like this 
```
HTTP/1.1 200 OK
Content-Type: application/json

{
  "pagination": {
    "total_results": 3,
    "total_pages": 2,
    "first": {
      "href": "https://api.example.org/v3/organizations/:guid/users?page=1&per_page=2"
    },
    "last": {
      "href": "https://api.example.org/v3/organizations/:guid/users?page=2&per_page=2"
    },
    "next": {
      "href": "https://api.example.org/v3/organizations/:guid/users?page=2&per_page=2"
    },
    "previous": null
  },
  "resources": [
     {
      "guid": "client_id",
      "created_at": "2019-03-08T01:06:19Z",
      "updated_at": "2019-03-08T01:06:19Z",
      "username": null,
      "presentation_name": "client_id",
      "origin": null,
      "metadata": {
        "labels": {},
        "annotations":{}
      },
      "links": {
        "self": {
          "href": "https://api.example.org/v3/users/3a5d3d89-3f89-4f05-8188-8a2b298c79d5"
        }
      }
    },
    {
      "guid": "9da93b89-3f89-4f05-7238-8a2b123c79l9",
      "created_at": "2019-03-08T01:06:19Z",
      "updated_at": "2019-03-08T01:06:19Z",
      "username": "some-name",
      "presentation_name": "some-name",
      "origin": "uaa",
      "metadata": {
        "labels": {},
        "annotations":{}
      },
      "links": {
        "self": {
          "href": "https://api.example.org/v3/users/9da93b89-3f89-4f05-7238-8a2b123c79l9"
        }
      }
    }
  ]
}
```

**Comment by cshollingsworth** [comment]
This feature is now included in the docs.
