### ISSUE TITLE
[TAS-E-184] Support Apple ARM architecture

### ISSUE THREAD

**Issue by a-b** [pivotal-cf/docs-pcf-pws#89]
### Background Information

Please fill out all of these fields!

* **Link(s) to Pivotal Tracker epic or story/stories:** [Link]
- https://www.pivotaltracker.com/story/show/179288139

* **Link(s) to any existing documentation:** [Link]
N/A

* **Versions to which this applies:** [Versions]
- CF CLI 8.4.0 https://github.com/cloudfoundry/cli/releases/tag/v8.4.0
- CF CLI 7.5.0 https://github.com/cloudfoundry/cli/releases/tag/v7.5.0

* **Slack user(s) or channel that we can contact (for clarification, review, etc.):** [Usernames or channel name]
https://cloudfoundry.slack.com/archives/C032824SM @interrupt

### Guidelines

Please include the following information in your write-up:

* Who is the target user--operator, developer, other?
All users

* What changed in the product, and why?
Added support of Apple ARM architecture to let users use cli on new Apple MACs with M1 and M2 processors based on ARM architecture.

* How does it work, in detail? How does the operator or developer use it?
They run CF CLI binary on ARM-based computers without an emulator.

* What are the benefits to customers?
More options where to run CF CLI

* Are there any example use cases that we can highlight?
Customers using a newer M1-based laptop now do not need to use an emulator.

Other things to remember:

* If the CLI is involved, please provide example steps, including example commands to run and example command output.
N/A

* Be sure to mention any extensions, plug-ins, or third-party tools the user will need to follow the documentation.
N/A

* If the UI is involved, please provide example steps **and screenshots!**
N/A

## Content

Customers using a newer M1-based laptop can use CF CLI without an emulator.

**Comment by anita-flegg** [comment]
Hi @a-b, I found this by going through the Tracker tickets, and it looks like it was not done. 
Would you provide some context? Were you thinking this should go in `about-app-autoscaler.html`?

**Comment by anita-flegg** [comment]
Looks like this should be in docs-cf-cli.
I added a note in `install-go-cli.html`.
