### ISSUE TITLE
[TAS-E-244] Golang upgrade

### ISSUE THREAD

**Issue by a-b** [pivotal-cf/docs-pcf-pws#90]
To submit content for the TAS IX team to use in writing documentation:

1. Fill out all fields in "Background Information".

1. Review the "Guidelines".

1. Under "Content", write your content, following the "Guidelines".

1. Click "Submit new issue".

We will follow up with you if necessary. Thank you!

### Background Information

Please fill out all of these fields!

* **Link(s) to Pivotal Tracker epic or story/stories:** [Link]
- https://www.pivotaltracker.com/story/show/182391478

* **Link(s) to any existing documentation:** [Link]
N/A

* **Versions to which this applies:** [Versions]
- https://github.com/cloudfoundry/cli/releases/tag/v8.3.0
- https://github.com/cloudfoundry/cli/releases/tag/v7.5.0

* **Slack user(s) or channel that we can contact (for clarification, review, etc.):** [Usernames or channel name]
https://cloudfoundry.slack.com/archives/C032824SM @Interrupt

### Guidelines

Please include the following information in your write-up:

* Who is the target user--operator, developer, other?
All

* What changed in the product, and why?
Binary was compiled using golang 1.17

* How does it work, in detail? How does the operator or developer use it?
They benefit from patched vulnerabilities

* What are the benefits to customers?
They benefit from patched vulnerabilities

* Are there any example use cases that we can highlight?
N/A

Other things to remember:

* If the CLI is involved, please provide example steps, including example commands to run and example command output.
N/A

* Be sure to mention any extensions, plug-ins, or third-party tools that the user will need in order to follow the documentation.
N/A

* If the UI is involved, please provide example steps **and screenshots!**
N/A

## Content

CF CLI binaries were released using golang 1.17

**Comment by fifthposition** [comment]
Thanks, @a-b!
