### ISSUE TITLE
[TAS-E-269] Apps Manager Jammy Jellyfish

### ISSUE THREAD

**Issue by a-b** [pivotal-cf/docs-pcf-pws#91]
To submit content for the TAS IX team to use in writing documentation:

1. Fill out all fields in "Background Information".

1. Review the "Guidelines".

1. Under "Content", write your content, following the "Guidelines".

1. Click "Submit new issue".

We will follow up with you if necessary. Thank you!

### Background Information

Please fill out all of these fields!

* **Link(s) to Pivotal Tracker epic or story/stories:** [Link]
- https://www.pivotaltracker.com/story/show/182870207
- https://www.pivotaltracker.com/story/show/182376528
- https://www.pivotaltracker.com/story/show/182458353
- https://www.pivotaltracker.com/story/show/182376501

* **Link(s) to any existing documentation:** [Link]
N/A

* **Versions to which this applies:** [Versions]
Apps Manager v677.0.6

* **Slack user(s) or channel that we can contact (for clarification, review, etc.):** [Usernames or channel name]
https://vmware.slack.com/archives/C055JEH48 @interrupt

### Guidelines

Please include the following information in your write-up:

* Who is the target user--operator, developer, other?
Operator

* What changed in the product, and why?
Upgraded stemcell used in Apps Manager tile, so it is up to date

* How does it work, in detail? How does the operator or developer use it?
The operator should make Linux Ubuntu Jammy Jellyfish stemcell available

* What are the benefits to customers?
Patched security vulnerabilities 

* Are there any example use cases that we can highlight?
N/A

Other things to remember:

* If the CLI is involved, please provide example steps, including example commands to run and example command output.
N/A

* Be sure to mention any extensions, plug-ins, or third-party tools that the user will need in order to follow the documentation.
N/A

* If the UI is involved, please provide example steps **and screenshots!**
N/A

## Content

This Apps Manager tile is shipped based on Ubuntu 22.04 LTS (Jammy Jellyfish) stemcell

**Comment by cshollingsworth** [comment]
This feature is now included in the docs.
