### ISSUE TITLE
TAS-E-246 and TAS-E-94 User Search

### ISSUE THREAD

**Issue by pivotalgeorge** [pivotal-cf/docs-pcf-pws#92]
To submit content for the TAS IX team to use in writing documentation:

1. Fill out all fields in "Background Information".

1. Review the "Guidelines".

1. Under "Content", write your content, following the "Guidelines".

1. Click "Submit new issue".

We will follow up with you if necessary. Thank you!

### Background Information

Please fill out all of these fields!

* **Link(s) to Pivotal Tracker epic or story/stories:** Epic [##4986435](https://www.pivotaltracker.com/epic/show/4986435), most of the work in this release done under [#182761604](https://www.pivotaltracker.com/story/show/182761604)
the required change to CAPI was done under [#182761790](https://www.pivotaltracker.com/story/show/182761790)

* **Link(s) to any existing documentation:** [User roles in Apps Manager](https://docs.pivotal.io/application-service/2-13/console/console-roles.html)

* **Versions to which this applies:** TAS 3.0

* **Slack user(s) or channel that we can contact (for clarification, review, etc.):** [#apps-manager](https://vmware.slack.com/archives/C055JEH48)

### Guidelines

Please include the following information in your write-up:

* Who is the target user--operator, developer, other?

* What changed in the product, and why?

* How does it work, in detail? How does the operator or developer use it?

* What are the benefits to customers?

* Are there any example use cases that we can highlight?

Other things to remember:

* If the CLI is involved, please provide example steps, including example commands to run and example command output.

* Be sure to mention any extensions, plug-ins, or third-party tools that the user will need in order to follow the documentation.

* If the UI is involved, please provide example steps **and screenshots!**

## Content

A search field is added to the Members tab of the Organization view, so that users can more easily find a specific member. The target user is either an operator or developer -- anyone with access to view Org Members.

The user navigates to an Organization they have access to (e.g. by clicking one of the orgs on the Apps Manager home screen), and then on the members tab of that Org.
The user types in a query in the Search members field of the "Search members" field, and presses enter to search. The members table changes from listing all members to the results of the search.
When the user clears the search field, the original full list of members is restored.

In orgs with a large number of users, it can take a while to locate a specific member, for example to grant or revoke manager/auditor access, or to remove someone from the org.
The previous process for this involves paging through all org members to look for the desired member.
With the addition of search to the org members page, this process now consists of a search query followed by the desired operation.

## Screenshots
In order
<img width="1792" alt="tas246-screenshot1" src="https://user-images.githubusercontent.com/16085413/191062311-08755001-7934-47f6-a646-2b1e110c68a2.png">
<img width="1792" alt="tas246-screenshot2" src="https://user-images.githubusercontent.com/16085413/191062328-9edd8a4a-e958-4910-a7f8-8fc8f8f9d415.png">
<img width="1792" alt="tas246-screenshot3" src="https://user-images.githubusercontent.com/16085413/191062467-39935143-cff7-414c-8149-8ac8c6e5d867.png">
<img width="1792" alt="tas246-screenshot4" src="https://user-images.githubusercontent.com/16085413/191062507-2d60d095-49cd-4291-bb82-323435cad6b4.png">
<img width="1792" alt="tas246-screenshot5" src="https://user-images.githubusercontent.com/16085413/191062518-527a1194-a807-4793-8297-52bed52bb538.png">
<img width="1792" alt="tas246-screenshot6" src="https://user-images.githubusercontent.com/16085413/191062527-f1a14d98-2cb9-4474-af0f-97297a4e22c8.png">

**Comment by cshollingsworth** [comment]
This feature is now included in the docs.
